spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:12345}
    url: jdbc:postgresql://${POSTGRES_DATABASE_URL:localhost:5432/rest-api}
springdoc:
  api-docs:
    path: /swagger-spec
